version: "3"
services:
  php:
    image: php7.2-web-sandbox
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    container_name: php7.2-web-sandbox
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    container_name: mysql5.7-web-sandbox
